/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AdminSettingsRouteImport } from './routes/_admin.settings'
import { Route as AdminNotificationsRouteImport } from './routes/_admin.notifications'
import { Route as AdminMembersRouteImport } from './routes/_admin.members'
import { Route as AdminDashboardRouteImport } from './routes/_admin.dashboard'
import { Route as AdminApplicationsRouteImport } from './routes/_admin.applications'
import { Route as AdminEventsListRouteImport } from './routes/_admin.events.list'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsListRoute = AdminEventsListRouteImport.update({
  id: '/events/list',
  path: '/events/list',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/applications': typeof AdminApplicationsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/members': typeof AdminMembersRoute
  '/notifications': typeof AdminNotificationsRoute
  '/settings': typeof AdminSettingsRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/events/list': typeof AdminEventsListRoute
}
export interface FileRoutesByTo {
  '/': typeof AdminRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/applications': typeof AdminApplicationsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/members': typeof AdminMembersRoute
  '/notifications': typeof AdminNotificationsRoute
  '/settings': typeof AdminSettingsRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/events/list': typeof AdminEventsListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_admin/applications': typeof AdminApplicationsRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/members': typeof AdminMembersRoute
  '/_admin/notifications': typeof AdminNotificationsRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_admin/events/list': typeof AdminEventsListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/applications'
    | '/dashboard'
    | '/members'
    | '/notifications'
    | '/settings'
    | '/auth/reset-password'
    | '/events/list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/applications'
    | '/dashboard'
    | '/members'
    | '/notifications'
    | '/settings'
    | '/auth/reset-password'
    | '/events/list'
  id:
    | '__root__'
    | '/_admin'
    | '/design-system'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_admin/applications'
    | '/_admin/dashboard'
    | '/_admin/members'
    | '/_admin/notifications'
    | '/_admin/settings'
    | '/auth/reset-password'
    | '/_admin/events/list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/notifications': {
      id: '/_admin/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/members': {
      id: '/_admin/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/applications': {
      id: '/_admin/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/events/list': {
      id: '/_admin/events/list'
      path: '/events/list'
      fullPath: '/events/list'
      preLoaderRoute: typeof AdminEventsListRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminEventsListRoute: typeof AdminEventsListRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminEventsListRoute: AdminEventsListRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
